services:
  app-service:
    build:
      context: pedidos/
    container_name: pedidos-service
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-service:5432/appdb
      PORT: 3000
    depends_on:
      - postgres-service
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run dev"

  postgres-service:
    image: postgres:17-alpine
    container_name: pedidos-service-postgres-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_service_data:/var/lib/postgresql/data
    restart: unless-stopped

  app-cardapio:
    build:
      context: cardapio/
    container_name: cardapio-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-cardapio:5432/appdb
      PORT: 3001
    depends_on:
      - postgres-cardapio
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run dev"

  postgres-cardapio:
    image: postgres:17-alpine
    container_name: cardapio-service-postgres-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_cardapio_data:/var/lib/postgresql/data
    restart: unless-stopped

  app-pagamento:
    build:
      context: pagamento/
    container_name: pagamento-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-pagamento:5432/appdb
      PORT: 3002
    depends_on:
      - postgres-pagamento
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run dev"

  postgres-pagamento:
    image: postgres:17-alpine
    container_name: pagamento-service-postgres-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_pagamento_data:/var/lib/postgresql/data
    restart: unless-stopped

  app-notificacao:
    build:
      context: notificacao/
    container_name: notificacao-service
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres-notificacao:5432/appdb
      PORT: 3003
    depends_on:
      - postgres-notificacao
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm run dev"

  postgres-notificacao:
    image: postgres:17-alpine
    container_name: notificacao-service-postgres-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_notificacao_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_service_data:
  postgres_cardapio_data:
  postgres_pagamento_data:
  postgres_notificacao_data:
